# Jekyll Configuration for MCU Documentation
# HardFOC Interface Wrapper Project

# Site Settings
title: "HardFOC Interface Wrapper"
description: "Comprehensive MCU interface wrapper for HardFOC systems with unified API across multiple MCU platforms"
baseurl: "/hf-internal-interface-wrap"
url: "https://n3b3x.github.io"

# Build Settings
markdown: kramdown
highlighter: rouge
theme: minima

# Collections
collections:
  api:
    output: true
    permalink: /:collection/:name/
  esp_api:
    output: true
    permalink: /:collection/:name/
  utils:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "api"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "esp_api"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "utils"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - README.md
  - LICENSE
  - examples/
  - inc/
  - src/
  - CMakeLists.txt
  - Doxyfile
  - .github/

# Include files that are normally excluded
include:
  - _pages

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Minima theme settings
minima:
  social_links:
    github: n3b3x
    twitter: n3b3x

# SEO settings
author: "N3b3x"
twitter:
  username: n3b3x
github:
  username: n3b3x

# ESP32 specific settings
esp32:
  version: "latest"
  mcu_support:
    - "ESP32"
    - "ESP32-S2"
    - "ESP32-S3"
    - "ESP32-C3"
  interfaces:
    - "GPIO"
    - "ADC"
    - "PWM"
    - "UART"
    - "SPI"
    - "I2C"
    - "CAN"
    - "WiFi"
    - "Bluetooth"
    - "NVS"
    - "PIO"
    - "Temperature"
