# Lychee Configuration for HardFOC Interface Wrapper
# Link checking for documentation

# Exclude patterns (array format)
exclude = [
    "http://localhost.*",
    "http://127.0.0.1.*",
    "http://0.0.0.0.*",
    "example.com",
    "test.com",
    "*.local",
    "*.dev"
]

# Include file patterns
include = [
    "**/*.md",
    "**/*.rst",
    "**/*.txt"
]

# Request configuration
[request]
timeout = 15
user_agent = "lychee-link-checker/esp32-docs"
retry = 3
retry_wait_time = 1
follow_redirects = true
max_redirects = 5
verify_ssl = true

# Output configuration
[output]
format = "text"
verbose = false
progress = true
color = true
summary = true
statistics = true

# Cache configuration
cache = true
cache_max_age = 3600

# Base URL for relative links
base_url = "https://n3b3x.github.io/hf-internal-interface-wrap"