var searchData=
[
  ['scripts_20guide_0',['ESP32 Interface Wrapper - Utility Scripts Guide',['../md_examples_2esp32_2scripts_2docs_2README__UTILITY__SCRIPTS.html',1,'']]],
  ['scripts_20overview_1',['ESP32 Interface Wrapper - Scripts Overview',['../md_examples_2esp32_2scripts_2docs_2README__SCRIPTS__OVERVIEW.html',1,'']]],
  ['sensor_20comprehensive_20test_20suite_2',['ESP32-C6 Temperature Sensor Comprehensive Test Suite',['../md_examples_2esp32_2docs_2README__TEMPERATURE__TEST.html',1,'']]],
  ['suite_3',['suite',['../md_examples_2esp32_2docs_2README__I2C__TEST.html',1,'ESP32 I2C Comprehensive Test Suite'],['../md_examples_2esp32_2docs_2README__ADC__TEST.html',1,'ESP32-C6 ADC Comprehensive Testing Suite'],['../md_examples_2esp32_2docs_2README__ASCII__ART__TEST.html',1,'ESP32-C6 ASCII Art Generator Comprehensive Test Suite'],['../md_examples_2esp32_2docs_2README__GPIO__TEST.html',1,'ESP32-C6 GPIO Comprehensive Test Suite'],['../md_examples_2esp32_2docs_2README__LOGGER__TEST.html',1,'ESP32-C6 Logger Comprehensive Test Suite'],['../md_examples_2esp32_2docs_2README__NVS__TEST.html',1,'ESP32-C6 NVS Comprehensive Test Suite'],['../md_examples_2esp32_2docs_2README__TEMPERATURE__TEST.html',1,'ESP32-C6 Temperature Sensor Comprehensive Test Suite']]],
  ['suite_20documentation_4',['suite documentation',['../md_examples_2esp32_2docs_2README__PWM__TEST.html',1,'ESP32 Family PWM Comprehensive Test Suite Documentation'],['../md_examples_2esp32_2docs_2README__PIO__TEST.html',1,'ESP32-C6 PIO Comprehensive Test Suite Documentation'],['../md_examples_2esp32_2docs_2README__UART__TESTING.html',1,'ESP32-C6 UART Comprehensive Test Suite Documentation']]],
  ['support_5',['Multi-Version ESP-IDF Support',['../md_examples_2esp32_2scripts_2docs_2README__MULTI__VERSION__IDF.html',1,'']]],
  ['system_20guide_6',['system guide',['../md_examples_2esp32_2scripts_2docs_2README__CONFIG__SYSTEM.html',1,'ESP32 HardFOC Interface Wrapper - Configuration System Guide'],['../md_examples_2esp32_2scripts_2docs_2README__FLASH__SYSTEM.html',1,'ESP32 HardFOC Interface Wrapper - Flash System Guide'],['../md_examples_2esp32_2scripts_2docs_2README__LOGGING__SYSTEM.html',1,'ESP32 HardFOC Interface Wrapper - Logging System Guide'],['../md_examples_2esp32_2scripts_2docs_2README__BUILD__SYSTEM.html',1,'ESP32 Interface Wrapper - Build System Guide']]]
];
