var hierarchy =
[
    [ "adc_queue_message_t", "structadc__queue__message__t.html", null ],
    [ "AsciiArtGenerator", "classAsciiArtGenerator.html", null ],
    [ "BaseAdc", "classBaseAdc.html", [
      [ "EspAdc", "classEspAdc.html", null ]
    ] ],
    [ "BaseBluetooth", "classBaseBluetooth.html", [
      [ "EspBluetooth", "classEspBluetooth.html", null ]
    ] ],
    [ "BaseCan", "classBaseCan.html", [
      [ "EspCan", "classEspCan.html", null ]
    ] ],
    [ "BaseGpio", "classBaseGpio.html", [
      [ "EspGpio", "classEspGpio.html", null ]
    ] ],
    [ "BaseI2c", "classBaseI2c.html", [
      [ "EspI2cDevice", "classEspI2cDevice.html", null ]
    ] ],
    [ "BaseLogger", "classBaseLogger.html", [
      [ "EspLogger", "classEspLogger.html", null ]
    ] ],
    [ "BaseNvs", "classBaseNvs.html", [
      [ "EspNvs", "classEspNvs.html", null ]
    ] ],
    [ "BasePeriodicTimer", "classBasePeriodicTimer.html", [
      [ "EspPeriodicTimer", "classEspPeriodicTimer.html", null ]
    ] ],
    [ "BasePio", "classBasePio.html", [
      [ "EspPio", "classEspPio.html", null ]
    ] ],
    [ "BasePwm", "classBasePwm.html", [
      [ "EspPwm", "classEspPwm.html", null ]
    ] ],
    [ "BaseSpi", "classBaseSpi.html", [
      [ "EspSpiDevice", "classEspSpiDevice.html", null ]
    ] ],
    [ "BaseTemperature", "classBaseTemperature.html", [
      [ "EspTemperature", "classEspTemperature.html", null ]
    ] ],
    [ "BaseUart", "classBaseUart.html", [
      [ "EspUart", "classEspUart.html", null ]
    ] ],
    [ "BaseWifi", "classBaseWifi.html", [
      [ "EspWifi", "classEspWifi.html", null ]
    ] ],
    [ "CallbackTestData", "structCallbackTestData.html", null ],
    [ "EspPio::ChannelState", "structEspPio_1_1ChannelState.html", null ],
    [ "EspPwm::ChannelState", "structEspPwm_1_1ChannelState.html", null ],
    [ "EspPwm::ComplementaryPair", "structEspPwm_1_1ComplementaryPair.html", null ],
    [ "DigitalOutputGuard", "classDigitalOutputGuard.html", null ],
    [ "esp_temp_config_t", "structesp__temp__config__t.html", null ],
    [ "esp_temp_range_info_t", "structesp__temp__range__info__t.html", null ],
    [ "esp_temp_state_t", "structesp__temp__state__t.html", null ],
    [ "EspI2cBus", "classEspI2cBus.html", null ],
    [ "EspSpiBus", "classEspSpiBus.html", null ],
    [ "EspWifiAdvancedConfig", "structEspWifiAdvancedConfig.html", null ],
    [ "hf_adc_calibration_config_t", "structhf__adc__calibration__config__t.html", null ],
    [ "hf_adc_channel_config_t", "structhf__adc__channel__config__t.html", null ],
    [ "hf_adc_continuous_config_t", "structhf__adc__continuous__config__t.html", null ],
    [ "hf_adc_continuous_data_t", "structhf__adc__continuous__data__t.html", null ],
    [ "hf_adc_diagnostics_t", "structhf__adc__diagnostics__t.html", null ],
    [ "hf_adc_filter_config_t", "structhf__adc__filter__config__t.html", null ],
    [ "hf_adc_monitor_config_t", "structhf__adc__monitor__config__t.html", null ],
    [ "hf_adc_monitor_event_t", "structhf__adc__monitor__event__t.html", null ],
    [ "hf_adc_statistics_t", "structhf__adc__statistics__t.html", null ],
    [ "hf_adc_unit_config_t", "structhf__adc__unit__config__t.html", null ],
    [ "hf_bluetooth_address_t", "structhf__bluetooth__address__t.html", null ],
    [ "hf_bluetooth_ble_config_t", "structhf__bluetooth__ble__config__t.html", null ],
    [ "hf_bluetooth_classic_config_t", "structhf__bluetooth__classic__config__t.html", null ],
    [ "hf_bluetooth_device_info_t", "structhf__bluetooth__device__info__t.html", null ],
    [ "hf_bluetooth_gatt_characteristic_t", "structhf__bluetooth__gatt__characteristic__t.html", null ],
    [ "hf_bluetooth_gatt_service_t", "structhf__bluetooth__gatt__service__t.html", null ],
    [ "hf_can_config_t", "structhf__can__config__t.html", null ],
    [ "hf_can_diagnostics_t", "structhf__can__diagnostics__t.html", null ],
    [ "hf_can_filter_config_t", "structhf__can__filter__config__t.html", null ],
    [ "hf_can_message_t", "structhf__can__message__t.html", null ],
    [ "hf_can_reception_info_t", "structhf__can__reception__info__t.html", null ],
    [ "hf_can_statistics_t", "structhf__can__statistics__t.html", null ],
    [ "hf_can_status_t", "structhf__can__status__t.html", null ],
    [ "hf_esp_can_config_t", "structhf__esp__can__config__t.html", null ],
    [ "hf_esp_can_error_info_t", "structhf__esp__can__error__info__t.html", null ],
    [ "hf_esp_can_filter_config_t", "structhf__esp__can__filter__config__t.html", null ],
    [ "hf_esp_can_state_info_t", "structhf__esp__can__state__info__t.html", null ],
    [ "hf_esp_can_timing_config_t", "structhf__esp__can__timing__config__t.html", null ],
    [ "hf_esp_can_tx_info_t", "structhf__esp__can__tx__info__t.html", null ],
    [ "hf_gpio_advanced_config_t", "structhf__gpio__advanced__config__t.html", null ],
    [ "hf_gpio_diagnostics_t", "structhf__gpio__diagnostics__t.html", null ],
    [ "hf_gpio_flex_filter_config_t", "structhf__gpio__flex__filter__config__t.html", null ],
    [ "hf_gpio_pin_capabilities_t", "structhf__gpio__pin__capabilities__t.html", null ],
    [ "hf_gpio_pin_filter_config_t", "structhf__gpio__pin__filter__config__t.html", null ],
    [ "hf_gpio_pin_info_t", "structhf__gpio__pin__info__t.html", null ],
    [ "hf_gpio_sleep_config_t", "structhf__gpio__sleep__config__t.html", null ],
    [ "hf_gpio_statistics_t", "structhf__gpio__statistics__t.html", null ],
    [ "hf_gpio_status_info_t", "structhf__gpio__status__info__t.html", null ],
    [ "hf_gpio_wakeup_config_t", "structhf__gpio__wakeup__config__t.html", null ],
    [ "hf_i2c_async_result_t", "structhf__i2c__async__result__t.html", null ],
    [ "hf_i2c_custom_command_t", "structhf__i2c__custom__command__t.html", null ],
    [ "hf_i2c_device_config_t", "structhf__i2c__device__config__t.html", null ],
    [ "hf_i2c_diagnostics_t", "structhf__i2c__diagnostics__t.html", null ],
    [ "hf_i2c_master_bus_config_t", "structhf__i2c__master__bus__config__t.html", null ],
    [ "hf_i2c_multi_buffer_transaction_t", "structhf__i2c__multi__buffer__transaction__t.html", null ],
    [ "hf_i2c_slave_config_t", "structhf__i2c__slave__config__t.html", null ],
    [ "hf_i2c_statistics_t", "structhf__i2c__statistics__t.html", null ],
    [ "hf_i2c_transaction_buffer_t", "structhf__i2c__transaction__buffer__t.html", null ],
    [ "hf_log_message_t", "structhf__log__message__t.html", null ],
    [ "hf_logger_config_t", "structhf__logger__config__t.html", null ],
    [ "hf_logger_diagnostics_t", "structhf__logger__diagnostics__t.html", null ],
    [ "hf_logger_statistics_t", "structhf__logger__statistics__t.html", null ],
    [ "hf_lp_io_config_t", "structhf__lp__io__config__t.html", null ],
    [ "hf_nvs_capabilities_t", "structhf__nvs__capabilities__t.html", null ],
    [ "hf_nvs_diagnostics_t", "structhf__nvs__diagnostics__t.html", null ],
    [ "hf_nvs_entry_info_t", "structhf__nvs__entry__info__t.html", null ],
    [ "hf_nvs_iterator_config_t", "structhf__nvs__iterator__config__t.html", null ],
    [ "hf_nvs_partition_config_t", "structhf__nvs__partition__config__t.html", null ],
    [ "hf_nvs_statistics_t", "structhf__nvs__statistics__t.html", null ],
    [ "hf_pio_capabilities_t", "structhf__pio__capabilities__t.html", null ],
    [ "hf_pio_channel_config_t", "structhf__pio__channel__config__t.html", null ],
    [ "hf_pio_channel_statistics_t", "structhf__pio__channel__statistics__t.html", null ],
    [ "hf_pio_channel_status_t", "structhf__pio__channel__status__t.html", null ],
    [ "hf_pio_diagnostics_t", "structhf__pio__diagnostics__t.html", null ],
    [ "hf_pio_statistics_t", "structhf__pio__statistics__t.html", null ],
    [ "hf_pio_symbol_t", "structhf__pio__symbol__t.html", null ],
    [ "hf_pwm_capabilities_t", "structhf__pwm__capabilities__t.html", null ],
    [ "hf_pwm_channel_config_t", "structhf__pwm__channel__config__t.html", null ],
    [ "hf_pwm_channel_status_t", "structhf__pwm__channel__status__t.html", null ],
    [ "hf_pwm_diagnostics_t", "structhf__pwm__diagnostics__t.html", null ],
    [ "hf_pwm_eviction_request_t", "structhf__pwm__eviction__request__t.html", null ],
    [ "hf_pwm_fade_config_t", "structhf__pwm__fade__config__t.html", null ],
    [ "hf_pwm_statistics_t", "structhf__pwm__statistics__t.html", null ],
    [ "hf_pwm_timing_config_t", "structhf__pwm__timing__config__t.html", null ],
    [ "hf_pwm_unit_config_t", "structhf__pwm__unit__config__t.html", null ],
    [ "hf_rmt_carrier_config_t", "structhf__rmt__carrier__config__t.html", null ],
    [ "hf_rmt_receive_config_t", "structhf__rmt__receive__config__t.html", null ],
    [ "hf_rmt_transmit_config_t", "structhf__rmt__transmit__config__t.html", null ],
    [ "hf_spi_bus_config_t", "structhf__spi__bus__config__t.html", null ],
    [ "hf_spi_device_config_t", "structhf__spi__device__config__t.html", null ],
    [ "hf_spi_diagnostics_t", "structhf__spi__diagnostics__t.html", null ],
    [ "hf_spi_statistics_t", "structhf__spi__statistics__t.html", null ],
    [ "hf_temp_config_t", "structhf__temp__config__t.html", null ],
    [ "hf_temp_diagnostics_t", "structhf__temp__diagnostics__t.html", null ],
    [ "hf_temp_reading_t", "structhf__temp__reading__t.html", null ],
    [ "hf_temp_sensor_info_t", "structhf__temp__sensor__info__t.html", null ],
    [ "hf_temp_statistics_t", "structhf__temp__statistics__t.html", null ],
    [ "hf_timer_diagnostics_t", "structhf__timer__diagnostics__t.html", null ],
    [ "hf_timer_statistics_t", "structhf__timer__statistics__t.html", null ],
    [ "hf_timer_stats_t", "structhf__timer__stats__t.html", null ],
    [ "hf_uart_config_t", "structhf__uart__config__t.html", null ],
    [ "hf_uart_diagnostics_t", "structhf__uart__diagnostics__t.html", null ],
    [ "hf_uart_event_t", "structhf__uart__event__t.html", null ],
    [ "hf_uart_flow_config_t", "structhf__uart__flow__config__t.html", null ],
    [ "hf_uart_irda_config_t", "structhf__uart__irda__config__t.html", null ],
    [ "hf_uart_pattern_config_t", "structhf__uart__pattern__config__t.html", null ],
    [ "hf_uart_pin_map_esp32c6_t", "structhf__uart__pin__map__esp32c6__t.html", null ],
    [ "hf_uart_power_config_t", "structhf__uart__power__config__t.html", null ],
    [ "hf_uart_rs485_config_t", "structhf__uart__rs485__config__t.html", null ],
    [ "hf_uart_statistics_t", "structhf__uart__statistics__t.html", null ],
    [ "hf_uart_wakeup_config_t", "structhf__uart__wakeup__config__t.html", null ],
    [ "hf_wifi_ap_config_t", "structhf__wifi__ap__config__t.html", null ],
    [ "hf_wifi_ip_info_t", "structhf__wifi__ip__info__t.html", null ],
    [ "hf_wifi_network_info_t", "structhf__wifi__network__info__t.html", null ],
    [ "hf_wifi_station_config_t", "structhf__wifi__station__config__t.html", null ],
    [ "HfEspWifiCalibration", "structHfEspWifiCalibration.html", null ],
    [ "HfEspWifiPerformanceConfig", "structHfEspWifiPerformanceConfig.html", null ],
    [ "HfEspWifiStats", "structHfEspWifiStats.html", null ],
    [ "InterruptStatus", "structInterruptStatus.html", null ],
    [ "EspAdc::MonitorContext", "structEspAdc_1_1MonitorContext.html", null ],
    [ "RtosMutex", "classRtosMutex.html", null ],
    [ "RtosSharedLock< SharedMutex >", "classRtosSharedLock.html", null ],
    [ "RtosSharedMutex", "classRtosSharedMutex.html", null ],
    [ "RtosTime", "classRtosTime.html", null ],
    [ "RtosUniqueLock< Mutex >", "classRtosUniqueLock.html", null ],
    [ "TestResults", "structTestResults.html", null ],
    [ "TestTaskContext", "structTestTaskContext.html", null ],
    [ "EspPwm::TimerState", "structEspPwm_1_1TimerState.html", null ],
    [ "EspUart::UartState", "structEspUart_1_1UartState.html", null ],
    [ "EspPwm::ValidationContext", "structEspPwm_1_1ValidationContext.html", null ],
    [ "EspPwm::ValidationResult", "structEspPwm_1_1ValidationResult.html", null ]
];