name: Clang Format
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format
      - name: Check formatting
        run: clang-format --dry-run --Werror inc/*.h src/*.cpp
