name: 📚 Documentation CI

on:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main]
    paths: ['docs/**', '*.md', 'README.md']

env:
  PROJECT_DIR: examples/esp32
  TOOLS_DIR: examples/esp32/scripts

permissions:
  contents: write
  pages: write
  id-token: write
  actions: read

concurrency:
  group: docs-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build documentation with linting and spell checking
  docs-build:
    uses: N3b3x/hf-espidf-ci-tools/.github/workflows/docs.yml@main
    with:
      doxygen_config: "Doxyfile"
      output_dir: "docs/doxygen/html"
      run_link_check: true
      link_check_paths: "docs/**,*.md,**/docs/**,README.md"
      run_markdown_lint: true
      markdown_lint_paths: "**/*.md"
      run_spell_check: false
      spell_check_paths: "**/*.md"
      spell_check_config: ".cspell.json"
      deploy_pages: ${{ github.ref == 'refs/heads/main' }}
