name: 📚 Documentation CI

on:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main]
    paths: 
      - 'docs/**'
      - '*.md'
      - 'README.md'
      - 'Doxyfile'
      - '_config.yml'
      - 'Gemfile'

env:
  PROJECT_DIR: examples/esp32
  TOOLS_DIR: examples/esp32/scripts
  ESP32_DOCS_VERSION: ${{ github.ref_name }}
  BUILD_TYPE: ${{ github.event_name == 'pull_request' && 'pr' || 'release' }}

permissions:
  contents: write
  pages: write
  id-token: write
  actions: read

concurrency:
  group: docs-ci-${{ github.ref }}
  cancel-in-progress: false  # Don't cancel documentation builds

jobs:
  # Build documentation with linting and spell checking
  docs-build:
    uses: N3b3x/hf-general-ci-tools/.github/workflows/docs.yml@main
    with:
      doxygen_config: "Doxyfile"
      output_dir: "docs/doxygen/html"
      # Jekyll integration for better presentation
      jekyll_enabled: true
      jekyll_theme: "minima"
      jekyll_config: "_config.yml"
      jekyll_source: "docs"
      jekyll_destination: "_site"
      # Link checking with enhanced features
      run_link_check: true
      link_check_paths: "docs/**,*.md,**/docs/**,README.md"
      # Markdown linting
      run_markdown_lint: true
      markdown_lint_paths: "**/*.md"
      # Spell checking (disabled for now, can be enabled later)
      run_spell_check: false
      spell_check_paths: "**/*.md"
      spell_check_config: ".cspell.json"
      # Deploy only on main branch
      deploy_pages: ${{ github.ref == 'refs/heads/main' }}
    secrets: inherit

  # Optional: Add a separate link check job for comprehensive validation
  link-check-comprehensive:
    if: github.event_name == 'pull_request'
    uses: N3b3x/hf-general-ci-tools/.github/workflows/docs-link-check.yml@main
    with:
      paths: "docs/**,*.md,**/docs/**,README.md"
      fail_on_errors: true
      timeout: "15"
      retry: "3"
      exclude_private: true
      exclude_mail: true
      verbose: false
