name: 📚 Documentation CI

on:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main]
    paths: ['docs/**', '*.md', 'README.md']

env:
  PROJECT_DIR: examples/esp32
  TOOLS_DIR: examples/esp32/scripts

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build documentation
  docs-build:
    uses: N3b3x/hf-espidf-ci-tools/.github/workflows/docs.yml@main
    with:
      project_dir: ${{ env.PROJECT_DIR }}
      project_tools_dir: ${{ env.TOOLS_DIR }}
      doxygen_config: "Doxyfile"
      output_dir: "docs/doxygen/html"
      run_link_check: true
      link_check_paths: "docs/**,*.md,**/docs/**,README.md"
      deploy_pages: ${{ github.ref == 'refs/heads/main' }}

  # Comprehensive link checking
  link-check-comprehensive:
    uses: N3b3x/hf-espidf-ci-tools/.github/workflows/link-check.yml@main
    with:
      paths: "docs/**,*.md,**/docs/**,README.md,**/*.md"
      fail_on_errors: true

  # Documentation linting
  docs-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Lint markdown files
        run: markdownlint "**/*.md" --ignore node_modules

  # Spell checking
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup cspell
        run: npm install -g cspell

      - name: Spell check
        run: cspell "**/*.md" --config .cspell.json
