name: Documentation • Build • Deploy • Link Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Permissions needed for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Cache Doxygen tools and APT packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/apt
            /var/cache/apt
          key: doxygen-tools-${{ runner.os }}-${{ hashFiles('Doxyfile') }}
          restore-keys: |
            doxygen-tools-${{ runner.os }}-
      
      - name: Check documentation links
        run: python3 docs/check_docs.py docs/index.md
      
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
      
      - name: Build documentation
        run: doxygen Doxyfile
      
      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/html
          retention-days: 7
      
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html
          force_orphan: true
