name: Documentation • Build • Deploy • Link Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Permissions needed for GitHub Pages deployment
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Cache Doxygen tools and APT packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/apt
            /var/cache/apt
          key: doxygen-tools-${{ runner.os }}-${{ hashFiles('Doxyfile', 'docs/**') }}
          restore-keys: |
            doxygen-tools-${{ runner.os }}-
      
      - name: Check documentation links
        run: python3 docs/check_docs.py docs/index.md
      
      - name: Install Doxygen
        run: |
          if ! command -v doxygen &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y doxygen graphviz
          else
            echo "Doxygen already installed"
          fi
      
      - name: Build documentation
        run: |
          echo "Building documentation with Doxygen..."
          echo "Current directory: $(pwd)"
          echo "Input directories exist check:"
          find inc/ src/ examples/ -maxdepth 1 -type d 2>/dev/null || echo "Some input directories missing"
          
          echo "Running Doxygen..."
          doxygen Doxyfile
          
          echo "Checking generated files..."
          echo "Output directory structure:"
          find docs/ -type d 2>/dev/null || echo "docs/ directory structure:"
          find docs/ -maxdepth 1 2>/dev/null || echo "docs/ directory not found"
          
          if [ -d "docs/doxygen" ]; then
            echo "docs/doxygen contents:"
            find docs/doxygen/ -maxdepth 1 2>/dev/null
            if [ -d "docs/doxygen/html" ]; then
              echo "docs/doxygen/html contents:"
              find docs/doxygen/html/ -maxdepth 1 2>/dev/null | head -10
              echo "HTML files found: $(find docs/doxygen/html -name "*.html" | wc -l)"
            else
              echo "docs/doxygen/html directory not found!"
            fi
          else
            echo "docs/doxygen directory not found!"
          fi
      
      - name: Upload documentation
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docs-html
          path: docs/doxygen/html/
          retention-days: 7
      
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/doxygen/html
          force_orphan: true
