name: 📦 Release ESP32 CI

on:
  push:
    branches: [release/*, main]
    tags: ['v*']
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

env:
  PROJECT_DIR: examples/esp32
  TOOLS_DIR: examples/esp32/scripts
  RELEASE_VERSION: ${{ github.event.inputs.release_version || github.ref_name }}

permissions:
  contents: write
  pull-requests: write
  security-events: write
  pages: write
  id-token: write

concurrency:
  group: release-ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # Comprehensive build for release
  build-release:
    uses: N3b3x/hf-espidf-ci-tools/.github/workflows/build.yml@v1
    with:
      project_dir: ${{ env.PROJECT_DIR }}
      project_tools_dir: ${{ env.TOOLS_DIR }}
      clean_build: true  # Clean build for release
      tools_repo_sha: ${{ github.sha }}

  # Strict linting for release
  lint-release:
    uses: N3b3x/hf-espidf-ci-tools/.github/workflows/lint.yml@v1
    with:
      paths: "src/**,inc/**,examples/**,components/**"
      auto_fix: false  # No auto-fix for release
      style: "file"
      tidy_checks: "readability-*,performance-*,modernize-*,cert-*"
      strict: true

  # Full security audit
  security-release:
    uses: N3b3x/hf-espidf-ci-tools/.github/workflows/security.yml@v1
    with:
      project_dir: ${{ env.PROJECT_DIR }}
      project_tools_dir: ${{ env.TOOLS_DIR }}
      scan_type: "all"
      run_codeql: true
      codeql_languages: "cpp,python"
      tools_repo_sha: ${{ github.sha }}

  # Comprehensive static analysis
  static-analysis-release:
    uses: N3b3x/hf-espidf-ci-tools/.github/workflows/static-analysis.yml@v1
    with:
      paths: "src inc examples components"
      std: "c++17"
      strict: true  # Fail on any issues

  # Build and deploy documentation
  docs-release:
    uses: N3b3x/hf-espidf-ci-tools/.github/workflows/docs.yml@v1
    with:
      project_dir: ${{ env.PROJECT_DIR }}
      doxygen_config: "Doxyfile"
      output_dir: "docs/doxygen/html"
      run_link_check: true
      deploy_pages: true

  # Create release artifacts
  create-release:
    needs: [build-release, lint-release, security-release, static-analysis-release, docs-release]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: fw-*
          merge-multiple: true
          path: artifacts/

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          body: |
            ## 🚀 HardFOC ESP32 Release ${{ env.RELEASE_VERSION }}
            
            ### 📦 Firmware Binaries
            - All firmware binaries are attached to this release
            - Built with ESP-IDF v5.5
            - Target: ESP32-C6
            
            ### 📚 Documentation
            - [Documentation](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/)
            
            ### 🛡️ Security
            - Full security audit completed
            - CodeQL analysis passed
            - No known vulnerabilities
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/
          asset_name: firmware-${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip
