---
name: 📚 Publish Documentation

on:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs-with-doxygen-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  # Build documentation with linting and spell checking
  publish-docs:
    uses: N3b3x/hf-general-ci-tools/.github/workflows/docs.yml@main
    with:
      checkout_recursive: true
      doxygen_config: "Doxyfile"

      # Jekyll configuration for this repo's docs
      jekyll_enabled: true
      jekyll_config: "docs/_config.yml"
      jekyll_source: "."
      jekyll_destination: "_site"
      jekyll_layouts_dir: "docs/_layouts"
      
      # Link checking
      run_link_check: true
      link_check_paths: "**/*.md"
      verbose: true

      # Markdown linting
      run_markdown_lint: true
      markdown_lint_paths: "**/*.md"
      
      # Spell checking (disabled for now, can be enabled later)
      run_spell_check: false
      spell_check_paths: "**/*.md"
      spell_check_config: ".cspell.json"
      
      # Deploy only on main branch
      deploy_pages: true
